### PR TITLE
Add chaos testing guide

### PR DESCRIPTION
**Pull request by chaitanyaenr**
### Description
This commit:
- Adds information around test methodology that needs to be embraced and
  best practices that an OpenShift cluster, platform and applications running
  on top of it should take into account for best user experience, performance,
  resilience and reliability.
- Adds test environment recommendations as to how and where to run chaos tests.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
The plan is to host this on github pages post review and merge like we discussed. Thanks.

**Comment by chaitanyaenr** [comment]
@rpattath @psuriset PTAL. Thanks.

**Review by paigerube14 — APPROVED** [review]
LGTM!

**Comment by rpattath** [comment]
LGTM, good work Ravi and Paige !

**Pull request merged**
