### PR TITLE
changing input params checks

### PR DESCRIPTION
**Pull request by agullon**

### CODE REVIEW

**Comment by agullon** [comment]
cc @chaitanyaenr

**Comment by chaitanyaenr** [comment]
@agullon minor nit: we might want to tweak the check( https://github.com/cloud-bulldozer/kraken/blob/56f71a8e36f00cb6fef0d743010493a762cb1bff/kraken/pvc/pvc_scenario.py#L47 ) to accommodate the case where the pod_name is set to None. Thoughts?

**Comment by agullon** [comment]
> @agullon minor nit: we might want to tweak the check(
> 
> https://github.com/cloud-bulldozer/kraken/blob/56f71a8e36f00cb6fef0d743010493a762cb1bff/kraken/pvc/pvc_scenario.py#L47
> 
> ) to accommodate the case where the pod_name is set to None. Thoughts?

fixed it

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Review by paigerube14 — APPROVED** [review]
LGTM

**Pull request merged**
