### PR TITLE
Fix dependency issues

### PR DESCRIPTION
**Pull request by chaitanyaenr**
### Description
This commit installs setuptools and tox as part of the requirements.

### CODE REVIEW

**Comment by chaitanyaenr** [comment]
Fixes https://github.com/cloud-bulldozer/kraken/issues/79.

**Comment by paigerube14** [comment]
Can we also add tox to the list here to install? 

I haven't been able to create a cluster yet today to test this.

**Comment by chaitanyaenr** [comment]
@paigerube14 Added tox to the list of requirements. PTAL.

**Comment by paigerube14** [comment]
LGTM

**Pull request merged**
