### PR TITLE
Update the workflow

### PR DESCRIPTION
**Pull request by chaitanyaenr**
### Description
This commit modifies the workflow diagram to add pieces that are
leveraged to determine pass/fail for the chaos scenarios.

### CODE REVIEW

**Comment by paigerube14** [comment]
Are you able to make the font's a little smaller just for the items in the bottom left so that they aren't as close together? 

The arrow directly to the right is a little wordy, what do you think of the below? 
"Injects deliberate failures through Kube and Cloud API's, then checks the recovery of the component under test"

**Comment by chaitanyaenr** [comment]
@paigerube14 makes sense, will update the font and text.

**Comment by paigerube14** [comment]
LGTM

**Review by paigerube14 — APPROVED** [review]
LGTM

**Pull request merged**
